### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by jdgirald** [nawforce/apex-link-gulp#5]
## Current Behavior

While retrieving the Standard objects, the node heap limit is reached. I tried with --max-old-space-size=8000 and still got the same error.

## Expected Behavior

Being able to retrieve Standard Objects when calling update method.

## Steps to Reproduce the Problem

  1. Call update method
  2. The standardSObjectReader promise throws an error

stacktrace:
```
<--- Last few GCs --->
[963:0x6788f40]    70752 ms: Scavenge (reduce) 4093.0 (4104.5) -> 4093.0 (4104.5) MB, 1.1 / 0.0 ms  (average mu = 0.972, current mu = 0.181) allocation failure 
[963:0x6788f40]    70767 ms: Mark-sweep (reduce) 4102.3 (4113.8) -> 4102.0 (4112.5) MB, 10.6 / 0.0 ms  (+ 16.6 ms in 5 steps since start of marking, biggest step 15.9 ms, walltime since start of marking 58 ms) (average mu = 0.957, current mu = 0.610) allo

<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00d90 node::Abort() [node]
 2: 0xa1823b node::FatalError(char const*, char const*) [node]
 3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xea6105  [node]
 6: 0xeb57dd v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xeb84de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xe79642 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
 9: 0xe71c54 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [node]
10: 0xe73cc1 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [node]
11: 0x1105635 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [node]
12: 0x11e0d23 v8::internal::RegExpImpl::IrregexpExec(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, v8::internal::Handle<v8::internal::RegExpMatchInfo>, v8::internal::RegExp::ExecQuirks) [node]
13: 0x120806c v8::internal::Runtime_StringReplaceNonGlobalRegExpWithFunction(int, unsigned long*, v8::internal::Isolate*) [node]
14: 0x15e7819  [node]
Aborted
```

## Environment

- Version: 1.1.0
- Platform: Linux
- Node.js Version: v16.13.1

**Comment by nawforce** [comment]
Thanks for this, I will take a look, can't think why it should be using that much.

**Comment by nawforce** [comment]
Sorry for taking so long to get this out, I ran into another problem that took a while to sort out. 

I have released a new version which stores the downloaded metadata in a temporary directory as it arrives until we have all of it before then copying that into the .apexlink directory. Hopefully that should resolve any memory issues. You might also find the sfdx cli command useful, https://www.npmjs.com/package/apexlink. I have set this up to just add to any existing metadata in the .apexlink directory so you can download in stages rather than having to do all in one go.

Having got various bit of feedback on how the current mechanism is working I am thinking I will likely re-work the UI that is surfaced in VSCode. It works OK for how I might use this but it's clear that we need something more flexible to cover all the cases.
